"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { useStore } from "@/lib/store"
import {
  Sparkles,
  ImageIcon,
  Video,
  Calendar,
  Plus,
  FileText,
  MessageSquare,
  Hash,
  Layers,
  Film,
  Type,
  Bot,
  Wand2,
  FileVideo,
} from "lucide-react"
import Link from "next/link"
import { AIChatAssistant } from "@/components/ai-chat-assistant"

export default function MarketingPage() {
  const { content, products } = useStore()

  const contentStats = {
    ready: content.filter((c) => c.status === "ready").length,
    scheduled: content.filter((c) => c.status === "scheduled").length,
    needsAssets: content.filter((c) => c.status === "drafting").length,
    posted: content.filter((c) => c.status === "posted").length,
  }

  const tools = [
    {
      title: "AI Content Generator",
      description: "AI-powered hooks, captions, CTAs, hashtags, carousel outlines, and reel scripts",
      icon: Sparkles,
      href: "/marketing/generator",
      features: ["AI Hooks", "Smart Captions", "CTAs", "Hashtags", "Carousels", "Reel Scripts"],
      isAI: true,
    },
    {
      title: "AI Photo Studio",
      description: "Generate stunning product photos and marketing images with AI",
      icon: ImageIcon,
      href: "/marketing/mockup",
      features: ["AI Images", "Product Mockups", "Social Graphics", "Pinterest Pins"],
      isAI: true,
    },
    {
      title: "AI Video Builder",
      description: "Create professional videos with AI-generated scripts and suggestions",
      icon: Video,
      href: "/marketing/video",
      features: ["AI Scripts", "Shot Lists", "Kinetic Text", "9:16 Export"],
      isAI: true,
    },
    {
      title: "AI Script Writer",
      description: "Professional scripts for reels, TikToks, and promotional videos",
      icon: FileVideo,
      href: "/marketing/script-writer",
      features: ["Reel Scripts", "TikTok Scripts", "Promo Videos", "Voice-over"],
      isAI: true,
    },
    {
      title: "Content Calendar",
      description: "Manage your content queue with ready, scheduled, and posted archives",
      icon: Calendar,
      href: "/marketing/calendar",
      features: ["Queue Management", "Scheduling", "Performance Notes"],
      isAI: false,
    },
  ]

  const generatorOutputs = [
    { icon: MessageSquare, label: "AI Hooks", description: "10 viral hooks generated by AI" },
    { icon: FileText, label: "Smart Captions", description: "3 lengths optimized by AI" },
    { icon: Type, label: "CTAs", description: "Conversion-focused options" },
    { icon: Hash, label: "Hashtags", description: "AI-curated trending sets" },
    { icon: Layers, label: "Carousels", description: "Slide-by-slide AI outlines" },
    { icon: Film, label: "Reels", description: "AI script + shot list" },
  ]

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div>
          <h1 className="font-[family-name:var(--font-playfair)] text-3xl font-bold text-foreground">
            Marketing Factory
          </h1>
          <p className="text-muted-foreground mt-1">
            AI-powered content engine. Generate and store everything marketing.
          </p>
        </div>
        <Button className="gap-2 bg-primary text-primary-foreground hover:bg-primary/90" asChild>
          <Link href="/marketing/content/new">
            <Plus className="h-4 w-4" />
            New Content
          </Link>
        </Button>
      </div>

      {/* Content Queue Stats */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Card className="bg-green-500/10 border-green-500/20">
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Ready to Post</p>
                <p className="text-3xl font-bold text-green-500">{contentStats.ready}</p>
              </div>
              <div className="h-12 w-12 rounded-full bg-green-500/20 flex items-center justify-center">
                <FileText className="h-6 w-6 text-green-500" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-blue-500/10 border-blue-500/20">
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Scheduled</p>
                <p className="text-3xl font-bold text-blue-500">{contentStats.scheduled}</p>
              </div>
              <div className="h-12 w-12 rounded-full bg-blue-500/20 flex items-center justify-center">
                <Calendar className="h-6 w-6 text-blue-500" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-amber-500/10 border-amber-500/20">
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Needs Assets</p>
                <p className="text-3xl font-bold text-amber-500">{contentStats.needsAssets}</p>
              </div>
              <div className="h-12 w-12 rounded-full bg-amber-500/20 flex items-center justify-center">
                <ImageIcon className="h-6 w-6 text-amber-500" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-primary/10 border-primary/20">
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Posted</p>
                <p className="text-3xl font-bold text-primary">{contentStats.posted}</p>
              </div>
              <div className="h-12 w-12 rounded-full bg-primary/20 flex items-center justify-center">
                <Sparkles className="h-6 w-6 text-primary" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Main Content Grid */}
      <div className="grid gap-6 lg:grid-cols-3">
        {/* Marketing Tools */}
        <div className="lg:col-span-2 space-y-4">
          <h2 className="text-lg font-semibold text-foreground flex items-center gap-2">
            <Wand2 className="h-5 w-5 text-primary" />
            AI Marketing Tools
          </h2>
          <div className="grid gap-4 md:grid-cols-2">
            {tools.map((tool) => (
              <Card key={tool.title} className="group hover:border-primary/50 transition-colors">
                <CardHeader>
                  <div className="flex items-start justify-between">
                    <div className="h-10 w-10 rounded-lg bg-primary/10 flex items-center justify-center">
                      <tool.icon className="h-5 w-5 text-primary" />
                    </div>
                    <div className="flex items-center gap-2">
                      {tool.isAI && (
                        <Badge variant="secondary" className="text-xs gap-1">
                          <Bot className="h-3 w-3" />
                          AI
                        </Badge>
                      )}
                      <Button variant="ghost" size="sm" asChild>
                        <Link href={tool.href}>Open</Link>
                      </Button>
                    </div>
                  </div>
                  <CardTitle className="text-lg mt-3">{tool.title}</CardTitle>
                  <p className="text-sm text-muted-foreground">{tool.description}</p>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-wrap gap-2">
                    {tool.features.map((feature) => (
                      <Badge key={feature} variant="secondary" className="text-xs">
                        {feature}
                      </Badge>
                    ))}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* AI Assistant Sidebar */}
        <div className="lg:col-span-1">
          <h2 className="text-lg font-semibold text-foreground flex items-center gap-2 mb-4">
            <Bot className="h-5 w-5 text-primary" />
            AI Assistant
          </h2>
          <AIChatAssistant />
        </div>
      </div>

      {/* Content Generator Outputs */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-primary" />
            AI-Powered Content Types
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {generatorOutputs.map((output) => (
              <div key={output.label} className="flex items-start gap-3 rounded-lg border border-border p-4 bg-card">
                <div className="h-8 w-8 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                  <output.icon className="h-4 w-4 text-primary" />
                </div>
                <div>
                  <p className="font-medium text-foreground">{output.label}</p>
                  <p className="text-sm text-muted-foreground">{output.description}</p>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
